version: '3.3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
    - 2021:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=qlcuahanggiaydb
    volumes:
    - mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


volumes:
  mysql_db:
    driver: local